# Generated by Django 4.1.5 on 2023-01-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('secondary_name', models.CharField(max_length=35)),
                ('third_name', models.CharField(blank=True, max_length=30)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
