# Generated by Django 4.1.5 on 2023-01-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('debit', models.BooleanField(blank=True)),
                ('credit', models.BooleanField(blank=True)),
            ],
        ),
    ]
