# Generated by Django 4.1.5 on 2023-02-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('db', 'Дебетовая'), ('cr', 'Кредитная')], default=1, max_length=35),
            preserve_default=False,
        ),
    ]
